
CATALOG = "analytics_dq_dev"
CATALOG_AUDIT = "analytics_audit"
SCHEMA_AUDIT  = "dev"
SCHEMA_METADATA  = "metadata"
SCHEMA_CONFIGURATION  = "configuration"
SCHEMA_RESULTS  = "results"
DQ_CATALOG = "analytics_dq_dev"
DQ_QUARANTINE_SCHEMA = "quarantine"
META_TABLE = f"{CATALOG}.{SCHEMA_METADATA}.table"        
META_PROJECT = f"{CATALOG}.{SCHEMA_METADATA}.project"  
CONFIG_RULE_TEMPLATE = f"{CATALOG}.{SCHEMA_CONFIGURATION}.rule_template"        
CONFIG_RULE_ASSIGNMENT = f"{CATALOG}.{SCHEMA_CONFIGURATION}.rule_assignment" 
APPLY_AT=f"{CATALOG}.{SCHEMA_CONFIGURATION}.apply_at"    
CONFIG_PARAMETERS = f"{CATALOG}.{SCHEMA_CONFIGURATION}.parameters"
RUN_POLICY = f"{CATALOG}.{SCHEMA_CONFIGURATION}.run_policy"
RESULT = f"{CATALOG}.{SCHEMA_RESULTS}.result"
RESULT_TABLE = f"{CATALOG}.{SCHEMA_RESULTS}.result_table"
RESULT_RULE = f"{CATALOG}.{SCHEMA_RESULTS}.result_rule"
TABLES_TO_BE_CHECKED = ["customers"]
AUDIT_LOG = f"{CATALOG_AUDIT}.{SCHEMA_AUDIT}.processing_job_status"
COMPLETED = 'completed'
RUNNING = 'running'
DQ_FAILED = 'dq failed'
LOG_JOB_TYPE = 'dq_framework'
FAILED = 'failed'
PROJECT_NAME = 'sas2py'
ERROR = 'error'
WARNING = 'warning'
PASS = 'pass'
CODE_ERROR = 'code_error'
ALL = 'all'
